language: generic
sudo: required 
services:
   - docker 

before_install:
  - docker build -t meddebhedil/docker_react  -f Dockerfile.dev .

script:
  - docker run -e CI=true meddebhedil/docker_react  npm run test  -- --covrage